apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Select the pods with labels matching this selector
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port the container is listening on
  type: LoadBalancer  # Expose the service outside the cluster (requires LoadBalancer support)
